/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __ROBOSHERLOCK_TRACKING_ALL_TYPES_H__
#define __ROBOSHERLOCK_TRACKING_ALL_TYPES_H__

#include <robosherlock_tracking/types/type_definitions.h>


#endif /* __ROBOSHERLOCK_TRACKING_ALL_TYPES_H__ */
