ae:
  name: demo
fixedflow:
  - CollectionReader
  - ImagePreprocessor
  - PointCloudFilter
  - NormalEstimator
  - PlaneAnnotator
  - ImageSegmentationAnnotator
  - PointCloudClusterExtractor
  - ClusterMerger
  - SacModelAnnotator
CollectionReader:
  camera_config_files: ['config_reconfig_demo.ini']
