/*
 * This file was generated by generate_typesystem.py.
 * Filename:    tf_types
 * Name:        tf
 * Description: No description given
 * Version:     1.0
 * Vendor:      None
 */
#ifndef __TF_TYPES_H__
#define __TF_TYPES_H__

#include <rs/feature_structure_proxy.h>
#include <rs/types/type_definitions.h>

namespace rs
{

/*
 * TF
 */
class Pose : public FeatureStructureProxy
{
private:
  void initFields()
  {
    rotation.init(this, "rotation");
    translation.init(this, "translation");
  }
public:
  // 3x3 rotation (bullet) matrix
  ArrayFeatureStructureEntry<double> rotation;
  // No description given
  ArrayFeatureStructureEntry<double> translation;

  Pose(const Pose &other) :
      FeatureStructureProxy(other)
  {
    initFields();
  }

  Pose(uima::FeatureStructure fs) :
      FeatureStructureProxy(fs)
  {
    initFields();
  }
};

/*
 * TF
 */
class StampedPose : public Pose
{
private:
  void initFields()
  {
    frame.init(this, "frame");
    timestamp.init(this, "timestamp");
  }
public:
  // No description given
  FeatureStructureEntry<std::string> frame;
  // No description given
  FeatureStructureEntry<INT64> timestamp;

  StampedPose(const StampedPose &other) :
      Pose(other)
  {
    initFields();
  }

  StampedPose(uima::FeatureStructure fs) :
      Pose(fs)
  {
    initFields();
  }
};

/*
 * TF
 */
class StampedTransform : public StampedPose
{
private:
  void initFields()
  {
    childFrame.init(this, "childFrame");
  }
public:
  // No description given
  FeatureStructureEntry<std::string> childFrame;

  StampedTransform(const StampedTransform &other) :
      StampedPose(other)
  {
    initFields();
  }

  StampedTransform(uima::FeatureStructure fs) :
      StampedPose(fs)
  {
    initFields();
  }
};

}

TYPE_TRAIT(rs::Pose, RS_TF_POSE)
TYPE_TRAIT(rs::StampedPose, RS_TF_STAMPEDPOSE)
TYPE_TRAIT(rs::StampedTransform, RS_TF_STAMPEDTRANSFORM)

#endif /* __TF_TYPES_H__ */
