set(${PROJECT_NAME}_NAMESPACE           ${NAMESPACE})
set(${PROJECT_NAME}_TYPESYSTEM_CPP_PATH ${TYPESYSTEM_CPP_PATH})
set(${PROJECT_NAME}_TYPESYSTEM_XML_PATH ${TYPESYSTEM_XML_PATH})
set(${PROJECT_NAME}_ANNOTATOR_PATH      ${ANNOTATOR_PATH})
set(${PROJECT_NAME}_ENGINE_PATH         ${ENGINE_PATH})

