/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __ROBOSHERLOCK_RECOGNITION_ALL_TYPES_H__
#define __ROBOSHERLOCK_RECOGNITION_ALL_TYPES_H__

#include <robosherlock_recognition/types/type_definitions.h>


#endif /* __ROBOSHERLOCK_RECOGNITION_ALL_TYPES_H__ */
