/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __ROBOSHERLOCK_ANNOTATIONS_TYPE_DEFINITIONS_H__
#define __ROBOSHERLOCK_ANNOTATIONS_TYPE_DEFINITIONS_H__


#endif /* __ROBOSHERLOCK_ANNOTATIONS_TYPE_DEFINITIONS_H__ */
