#!/bin/bash
BACKUP_PWD=${PWD}
BACKUP_OLDPWD=${OLDPWD}

WS="$( dirname $( dirname $(rospack find robosherlock)))"

WS_DEB=${WS}/debug
WS_RELDEB=${WS}/reldeb
WS_REL=${WS}/release

BUILD=/build
DEVEL=/devel

BUILD_TYPE="-DCMAKE_BUILD_TYPE="

case "$1" in
    'debug' | 'deb')
  mkdir -p "${WS_DEB}${BUILD}"
  mkdir -p "${WS_DEB}${DEVEL}"
  ln -sfn "${WS_DEB}${BUILD}" "${WS}${BUILD}"
  ln -sfn "${WS_DEB}${DEVEL}" "${WS}${DEVEL}"
  BUILD_TYPE=${BUILD_TYPE}"Debug"
  ;;
  
    'reldeb' | 'reb')
  mkdir -p "${WS_RELDEB}${BUILD}"
  mkdir -p "${WS_RELDEB}${DEVEL}"
  ln -sfn "${WS_RELDEB}${BUILD}" "${WS}${BUILD}"
  ln -sfn "${WS_RELDEB}${DEVEL}" "${WS}${DEVEL}"
  BUILD_TYPE=${BUILD_TYPE}"RelWithDebInfo"
  ;;
  
    'release' | 'rel')
  mkdir -p "${WS_REL}${BUILD}"
  mkdir -p "${WS_REL}${DEVEL}"
  ln -sfn "${WS_REL}${BUILD}" "${WS}${BUILD}"
  ln -sfn "${WS_REL}${DEVEL}" "${WS}${DEVEL}"
  BUILD_TYPE=${BUILD_TYPE}"Release"
  ;;
  
    'clean')
  rm -rf "${WS_DEB}"
  rm -rf "${WS_RELDEB}"
  rm -rf "${WS_REL}"

  rm "${WS}${BUILD}"
  rm "${WS}${DEVEL}"
  exit 0
  ;;
  
    *)
  echo "Usage: `basename $0` [configuration] <additional parameters to catkin_make>"
  echo "Configurations:"
  echo "  debug   | deb  - build in debug mode"
  echo "  reldeb  | reb  - build in release with debug info mode"
  echo "  release | rel  - build in release mode"
  echo "  clean          - clean all build and devel folders"
  exit 0
  ;;
esac

cd ${WS}
catkin_make ${BUILD_TYPE} ${RS_BUILD_DEFAULTS} ${@:2}
cd ${BACKUP_PWD}
export OLDPWD="${BACKUP_OLDPWD}"

exit 0
